Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: organizations/orderer-org/orderers/orderer.degree.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.degree.com:7050

  - &AttestationOrg
    Name: AttestationOrg
    ID: AttestationMSP
    MSPDir: organizations/attestation-org/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AttestationMSP.admin', 'AttestationMSP.peer', 'AttestationMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('AttestationMSP.admin', 'AttestationMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('AttestationMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('AttestationMSP.peer')"
    AnchorPeers:
      - Host: peer0.attestation-org
        Port: 7051

  - &UniversityOrg
    Name: UniversityOrg
    ID: UniversityMSP
    MSPDir: organizations/university-org/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('UniversityMSP.admin', 'UniversityMSP.peer', 'UniversityMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('UniversityMSP.admin', 'UniversityMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('UniversityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('UniversityMSP.peer')"
    AnchorPeers:
      - Host: peer0.university-org
        Port: 8051

  - &EmployerOrg
    Name: EmployerOrg
    ID: EmployerMSP
    MSPDir: organizations/employer-org/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('EmployerMSP.admin', 'EmployerMSP.peer', 'EmployerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('EmployerMSP.admin', 'EmployerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('EmployerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('EmployerMSP.peer')"
    AnchorPeers:
      - Host: peer0.employer-org
        Port: 9051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer.degree.com
        Port: 7050
        ClientTLSCert: organizations/orderer-org/orderers/orderer.degree.com/tls/server.crt
        ServerTLSCert: organizations/orderer-org/orderers/orderer.degree.com/tls/server.crt
  Addresses:
    - orderer.degree.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  DegreeOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      DegreeConsortium:
        Organizations:
          - *AttestationOrg
          - *UniversityOrg
          - *EmployerOrg

  DegreeChannel:
    Consortium: DegreeConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *AttestationOrg
        - *UniversityOrg
        - *EmployerOrg
      Capabilities:
        <<: *ApplicationCapabilities