# crypto-config.yaml
# Configuration for generating cryptographic materials using cryptogen tool

OrdererOrgs:
  - Name: Orderer
    Domain: degree.com
    EnableNodeOUs: false
    Specs:
      - Hostname: orderer
    Users:
      Count: 1

PeerOrgs:
  - Name: AttestationOrg
    Domain: attestation-org
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 3

  - Name: UniversityOrg
    Domain: university-org
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 3

  - Name: EmployerOrg
    Domain: employer-org
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 3