# docker-compose.simple.yml - For testing without blockchain
networks:
  degree-network:
    driver: bridge

volumes:
  postgres-data:

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: degree-postgres
    environment:
      POSTGRES_DB: degree_attestation
      POSTGRES_USER: degree_user
      POSTGRES_PASSWORD: degree_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - degree-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: degree-redis
    ports:
      - "6379:6379"
    networks:
      - degree-network
    restart: unless-stopped

  # Attestation Authority Application
  attestation-authority:
    build:
      context: .
      dockerfile: applications/attestation-authority/Dockerfile
    container_name: attestation-authority
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/degree_attestation
      SPRING_DATASOURCE_USERNAME: degree_user
      SPRING_DATASOURCE_PASSWORD: degree_password
      # Disable blockchain for testing
      FABRIC_NETWORK_CONFIG_PATH: ""
      FABRIC_WALLET_PATH: ""
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - degree-network
    restart: unless-stopped

  # University Portal
  university-portal:
    build:
      context: .
      dockerfile: applications/university-portal/Dockerfile
    container_name: university-portal
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/degree_attestation
      SPRING_DATASOURCE_USERNAME: degree_user
      SPRING_DATASOURCE_PASSWORD: degree_password
      UNIVERSITY_CODE: UNI001
      # Disable blockchain for testing
      FABRIC_NETWORK_CONFIG_PATH: ""
      FABRIC_WALLET_PATH: ""
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - degree-network
    restart: unless-stopped

  # Employer Portal
  employer-portal:
    build:
      context: .
      dockerfile: applications/employer-portal/Dockerfile
    container_name: employer-portal
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/degree_attestation
      SPRING_DATASOURCE_USERNAME: degree_user
      SPRING_DATASOURCE_PASSWORD: degree_password
      # Disable blockchain for testing
      FABRIC_NETWORK_CONFIG_PATH: ""
      FABRIC_WALLET_PATH: ""
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - degree-network
    restart: unless-stopped

  # API Gateway
#  api-gateway:
#    build:
#      context: .
#      dockerfile: applications/api-gateway/Dockerfile
#    container_name: api-gateway
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      ATTESTATION_AUTHORITY_URL: http://attestation-authority:8080
#      UNIVERSITY_PORTAL_URL: http://university-portal:8080
#      EMPLOYER_PORTAL_URL: http://employer-portal:8080
#    ports:
#     - "8000:8080"
#    depends_on:
#      - redis
#      - attestation-authority
#      - university-portal
#      - employer-portal
#    networks:
#      - degree-network
#    restart: unless-stopped